name: Update Gist

on:
  push:
    branches: master

  schedule:
    - cron: "0 */2 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 010f1f07bf85e67f8bf56d24510fb285
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
